name: jgalaxian
version: "1.1.0"
summary: A Java Galaxian clone
description: |
  JGalaxian is a Java-based Galaxian clone.
confinement: strict
grade: stable
base: core18

apps:
  jgalaxian:
    command: usr/bin/jg-snap
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      ALSA_CONFIG_PATH: ${SNAP}/etc/asound.conf
      # Needed for fontconfig
      XDG_DATA_HOME: ${SNAP}/usr/share
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
    plugs: [x11,pulseaudio,audio-playback]
    #extensions: [ gnome-3-28 ]

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF

  jgalaxian:
    plugin: maven
    source-type: local
    source: .
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jdk
      - libpulse0
      - libasound2-plugins
      - x11-utils
    organize:
      ${SNAPCRAFT_PART_BUILD}/target/dep-jars/AudioCue-master-ddd83f721d-1.jar: jar/dep-jars/AudioCue-master-ddd83f721d-1.jar
      ${SNAPCRAFT_PART_BUILD}/jg-snap: usr/bin/jg-snap

